server:
  port: 8080

  servlet:
    ### UTF-8 ###
    encoding:
      force: true # UTF-8이 SpringBoot 2.x.x 에서는 기본이다.

spring:
  #H2 DataBase
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/cache-DB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  ### JPA 설정 ###
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
        generate_statistics: true